<a href="https://colab.research.google.com/github/Shirouky/lab4-Data-analysis/blob/main/LW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Базовые функции

In [ ]:
import pandas as pd

def import_xlsx():
  FILE_NAME = "DataFrame beads (3).xlsx"
  df = pd.read_excel(FILE_NAME)
  return df

In [ ]:
def save_xlsx(df):
  df.to_excel("DataFrame.xlsx", index=False)

In [ ]:
def print_distribution(df, column):
  counts = df[column].value_counts()
  print(f"Распределение {column} по категориям:")
  for category, count in counts.items():
      print(f"{category}: {count} объектов")

In [ ]:
df = import_xlsx()

# Задание 1

In [ ]:
def categorize_column(df, column):
  category_dict = {}
  print_distribution(df, column)
  unique_values = list(df[column].unique())

  for i in range(len(unique_values)):
    category_dict[unique_values[i]] = i + 1
  df[f"{column}_category"] = df[column].map(category_dict)

  print_distribution(df, f"{column}_category")
  return df

In [ ]:
df = categorize_column(df, "size")

Распределение size по категориям:
10/0: 440 объектов
08/0: 3 объектов
11/0: 1 объектов
Распределение size_category по категориям:
1: 440 объектов
2: 3 объектов
3: 1 объектов

# Задание 2

In [ ]:
def sampling_column(df, column, labels):
  print_distribution(df, column)
  df[f"{column}_category"] = pd.cut(df[column], bins=len(labels), labels=labels, include_lowest=True)
  print_distribution(df, f"{column}_category")
  print("\nПолучившиеся интервалы:")
  print(pd.cut(df[column], bins=len(labels), include_lowest=True).cat.categories)
  return df

df = sampling_column(df, "price", ["Низкая", "Средняя", "Высокая", "Очень высокая"])

Распределение price по категориям:
181: 133 объектов
184: 107 объектов
185: 65 объектов
212: 55 объектов
197: 19 объектов
216: 12 объектов
225: 9 объектов
209: 6 объектов
283: 5 объектов
208: 5 объектов
214: 5 объектов
220: 3 объектов
215: 2 объектов
179: 2 объектов
282: 2 объектов
178: 2 объектов
207: 1 объектов
187: 1 объектов
183: 1 объектов
371: 1 объектов
517: 1 объектов
194: 1 объектов
186: 1 объектов
196: 1 объектов
210: 1 объектов
203: 1 объектов
217: 1 объектов
268: 1 объектов
Распределение price_category по категориям:
Низкая: 434 объектов
Средняя: 8 объектов
Высокая: 1 объектов
Очень высокая: 1 объектов

Получившиеся интервалы:
IntervalIndex([(177.66, 262.75], (262.75, 347.5], (347.5, 432.25],
               (432.25, 517.0]],
              dtype='interval[float64, right]')

In [ ]:
def get_binary(column):
  return pd.get_dummies(column.astype(str))

binary_df = get_binary(df["price_category"])
binary_df

     Высокая  Низкая  Очень высокая  Средняя
0      False    True          False    False
1      False    True          False    False
2      False    True          False    False
3      False    True          False    False
4      False    True          False    False
..       ...     ...            ...      ...
439    False    True          False    False
440    False    True          False    False
441    False    True          False    False
442    False    True          False    False
443    False    True          False    False

[444 rows x 4 columns]

In [ ]:
# combined_df = pd.concat([df, binary_df], axis=1)
combined_df = df.join(binary_df)
combined_df

,id_web,code,type,size,weight,color,sale,price,old_price,currency,...,type_category,code_category,color_code_category,concat_price,size_category,price_category,Высокая,Низкая,Очень высокая,Средняя
0,2687,48013,круглый,10/0,50,жёлтый,-4,185,192,RUB,...,1,23,257,48013/185,1,Низкая,False,True,False,False
1,203111,08789,круглый,10/0,50,матовый крашенный из середины оранжевый,-6,197,192,RUB,...,1,63,256,08789/197,1,Низкая,False,True,False,False
2,202340,03461,круглый,10/0,50,зеленый,-6,184,192,RUB,...,1,2,255,03461/184,1,Низкая,False,True,False,False
3,193607,03284,круглый,10/0,50,оранжевый,-6,184,169,RUB,...,1,2,254,03284/184,1,Низкая,False,True,False,False
4,168486,38652,круглый,10/0,50,серо-зелёный,-6,181,192,RUB,...,1,24,253,38652/181,1,Низкая,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,194296,17050,круглый,10/0,50,золотистый матовый,-6,181,192,RUB,...,1,20,2,17050/181,1,Низкая,False,True,False,False
440,975,17050,круглый,10/0,50,золотистый,-6,181,192,RUB,...,1,20,2,17050/181,1,Низкая,False,True,False,False
441,168454,37050,круглый,10/0,50,тёмно-кремовый,-6,181,192,RUB,...,1,18,2,37050/181,1,Низкая,False,True,False,False
442,200118,97050,круглый,10/0,50,красный матовый,-7,216,129,RUB,...,1,11,2,97050/216,1,Низкая,False,True,False,False
443,168458,97050,круглый,10/0,50,оранжево-красный,-6,181,192,RUB,...,1,11,2,97050/181,1,Низкая,False,True,False,False